require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 135

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Metrics/ClassLength:
  Max: 120
  Exclude:
    - 'lib/keyrod/cli.rb'

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

RSpec/MultipleExpectations:
  Enabled: false